# Generated by Django 5.1.4 on 2025-01-02 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='productos/principal/')),
                ('imagen_extra_1', models.ImageField(blank=True, null=True, upload_to='productos/extra/')),
                ('imagen_extra_2', models.ImageField(blank=True, null=True, upload_to='productos/extra/')),
                ('imagen_extra_3', models.ImageField(blank=True, null=True, upload_to='productos/extra/')),
                ('imagen_extra_4', models.ImageField(blank=True, null=True, upload_to='productos/extra/')),
            ],
        ),
        migrations.CreateModel(
            name='Guitarra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('galeria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalogo.galeria')),
            ],
        ),
    ]
