# Generated by Django 5.1.4 on 2025-01-06 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_accesorios_maderas'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitarra',
            name='acabado',
            field=models.CharField(default='semi-mate', max_length=50),
        ),
        migrations.AddField(
            model_name='guitarra',
            name='accesorios',
            field=models.ManyToManyField(blank=True, to='catalogo.accesorios'),
        ),
        migrations.AddField(
            model_name='guitarra',
            name='color',
            field=models.CharField(default='natural', max_length=50),
        ),
        migrations.AddField(
            model_name='guitarra',
            name='curvas',
            field=models.CharField(default='5', max_length=50),
        ),
        migrations.AddField(
            model_name='guitarra',
            name='maderas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.maderas'),
        ),
    ]
