# Generated by Django 5.1.4 on 2025-01-06 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_extras_alter_guitarra_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extras',
        ),
    ]
