# Generated by Django 5.1.4 on 2025-01-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_delete_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitarra',
            name='curvas',
            field=models.IntegerField(default=0),
        ),
    ]
