# Generated by Django 5.1.4 on 2025-01-08 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_acabado_alter_guitarra_acabado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guitarra',
            new_name='Bajoquinto',
        ),
    ]
