# Generated by Django 5.1.4 on 2025-01-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_rename_guitarra_bajoquinto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(upload_to='gamas_img/')),
            ],
        ),
    ]
